package com.tencent.mm.plugin.sns.ui;

import com.tencent.mm.l.a;
import com.tencent.mm.plugin.sns.data.d;
import com.tencent.mm.plugin.sns.storage.b;
import com.tencent.mm.plugin.sns.storage.m;
import com.tencent.mm.protocal.c.aqs;
import com.tencent.mm.protocal.c.bjv;
import com.tencent.mm.protocal.c.bnp;

public final class ay {
    public int aac;
    public String jKk;
    public String mAppName;
    public bjv qyf;
    public m qyg;
    public bnp qyk;
    public d rJG;
    public CharSequence rJH = null;
    public a rJI;
    public String rJJ;
    public long rJK;
    public String rJL;
    public int rJM;
    public int rJN;
    public int rJO;
    public boolean rJP;
    public String rJQ;
    public String rJR;
    public com.tencent.mm.plugin.sns.storage.a rJS;
    public b rJT;
    public String rJU;
    public String rJV;
    public String rJW;
    public String rJX;
    public String rJY;
    public boolean rJZ;
    public aqs rKA;
    public boolean rKa;
    public boolean rKb;
    public int rKc;
    public boolean rKd;
    public String rKe;
    public boolean rKf;
    public boolean rKg;
    public boolean rKh;
    public boolean rKi;
    public String rKj;
    public String rKk;
    public boolean rKl;
    public boolean rKm;
    public int rKn;
    public boolean rKo;
    public boolean rKp;
    public String rKq;
    public boolean rKr;
    public boolean rKs;
    public int rKt;
    public double rKu;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rKv;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rKw;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rKx;
    public boolean rKy;
    public String rKz;
    public boolean rrf;
    public String rsD;
}
