package com.tencent.mm.compatible.d;

import com.tencent.mm.sdk.platformtools.x;

public final class k {
    public int gEC = -1;
    public int gED = -1;
    public int gEE = -1;
    public int gEF = -1;
    public int gEG = -1;
    public int gEH = -1;
    public int gEI = -1;
    public int gEJ = -1;
    public boolean gEK = false;
    public int gEL = -1;
    public int gEM = -1;
    public int gEN = -1;
    public int gEO = -1;
    public int gEP = -1;
    public int gEQ = -1;
    public int gER = -1;
    public int gES = -1;
    public int gET = -1;
    public int gEU = -1;
    public int gEV = -1;
    public int gEW = -1;
    public int gEX = -1;
    public int gEY = -1;
    public int gEZ = -1;
    public int gFA = -1;
    public int gFa = -1;
    public int gFb = -1;
    public int gFc = -1;
    public int gFd = -1;
    public double gFe = -1.0d;
    public int gFf = -1;
    public int gFg = -1;
    public int gFh = -1;
    public int gFi = -1;
    public String gFj = null;
    public String gFk = null;
    public String gFl = null;
    public String gFm = null;
    public String gFn = null;
    public String gFo = null;
    public String gFp = null;
    public String gFq = null;
    public String gFr = null;
    public String gFs = null;
    public String gFt = null;
    public String gFu = null;
    public String gFv = null;
    public int gFw = -1;
    public int gFx = 2;
    public int gFy = 1;
    public int gFz = 1;

    public k() {
        reset();
    }

    public final void reset() {
        this.gEC = -1;
        this.gED = -1;
        this.gEE = -1;
        this.gEF = -1;
        this.gEG = -1;
        this.gEH = -1;
        this.gEJ = -1;
        this.gEI = -1;
        this.gEM = -1;
        this.gEN = -1;
        this.gEO = -1;
        this.gEP = -1;
        this.gEK = false;
        this.gEL = -1;
        this.gEQ = -1;
        this.gER = -1;
        this.gES = -1;
        this.gET = -1;
        this.gEU = -1;
        this.gEX = -1;
        this.gEW = -1;
        this.gEY = -1;
        this.gEZ = -1;
        this.gEV = -1;
        this.gEY = -1;
        this.gEZ = -1;
        this.gFc = -1;
        this.gFf = -1;
        this.gFg = -1;
        this.gFh = -1;
        this.gFi = -1;
        this.gFj = null;
        this.gFk = null;
        this.gFl = null;
        this.gFm = null;
        this.gFa = -1;
        this.gFn = null;
        this.gFo = null;
        this.gFp = null;
        this.gFq = null;
        this.gFr = null;
        this.gFs = null;
        this.gFb = -1;
        this.gFt = null;
        this.gFu = null;
        this.gFv = null;
        this.gFw = -1;
        this.gFx = 2;
        this.gFy = 1;
        this.gFz = 1;
        this.gFd = -1;
    }

    public final void dump() {
        x.d("MicroMsg.CommonInfo", "js " + this.gEC);
        x.d("MicroMsg.CommonInfo", "stopBluetoothInBR " + this.gED);
        x.d("MicroMsg.CommonInfo", "stopBluetoothInBU " + this.gEE);
        x.d("MicroMsg.CommonInfo", "setBluetoothScoOn " + this.gEG);
        x.d("MicroMsg.CommonInfo", "startBluetoothSco " + this.gEF);
        x.d("MicroMsg.CommonInfo", "voiceSearchFastMode " + this.gEH);
        x.d("MicroMsg.CommonInfo", "pcmReadMode " + this.gEJ);
        x.d("MicroMsg.CommonInfo", "pcmBufferRate " + this.gEI);
        x.d("MicroMsg.CommonInfo", "audioPrePro " + this.gEM);
        x.d("MicroMsg.CommonInfo", "voicemsgfd " + this.gEN);
        x.d("MicroMsg.CommonInfo", "htcvoicemode " + this.gEO);
        x.d("MicroMsg.CommonInfo", "samsungvoicemode " + this.gEP);
        x.d("MicroMsg.CommonInfo", "speexBufferRate " + this.gEQ);
        x.d("MicroMsg.CommonInfo", "linespe " + this.gER);
        x.d("MicroMsg.CommonInfo", "fixspan " + this.gFc);
        x.d("MicroMsg.CommonInfo", "extvideo " + this.gES);
        x.d("MicroMsg.CommonInfo", "extvideosam " + this.gET);
        x.d("MicroMsg.CommonInfo", "sysvideodegree " + this.gEU);
        x.d("MicroMsg.CommonInfo", "mmnotify " + this.gEX);
        x.d("MicroMsg.CommonInfo", "extsharevcard " + this.gEW);
        x.d("MicroMsg.CommonInfo", "audioformat " + this.gEY);
        x.d("MicroMsg.CommonInfo", "qrcam " + this.gEZ);
        x.d("MicroMsg.CommonInfo", "mBase " + this.gFj);
        x.d("MicroMsg.CommonInfo", "mPackageInfo " + this.gFk);
        x.d("MicroMsg.CommonInfo", "mClassLoader " + this.gFl);
        x.d("MicroMsg.CommonInfo", "mResources " + this.gFm);
        x.d("MicroMsg.CommonInfo", "sysvideofp " + this.gFa);
        x.d("MicroMsg.CommonInfo", "extstoragedir " + this.gFn);
        x.d("MicroMsg.CommonInfo", "extpubdir " + this.gFo);
        x.d("MicroMsg.CommonInfo", "extdatadir " + this.gFp);
        x.d("MicroMsg.CommonInfo", "extrootdir " + this.gFq);
        x.d("MicroMsg.CommonInfo", "extstoragestate " + this.gFr);
        x.d("MicroMsg.CommonInfo", "extcachedir " + this.gFs);
        x.d("MicroMsg.CommonInfo", "extvideoplayer " + this.gFb);
        x.d("MicroMsg.CommonInfo", "loadDrawable " + this.gFt);
        x.d("MicroMsg.CommonInfo", "loadXmlResourceParser " + this.gFu);
        x.d("MicroMsg.CommonInfo", "voipAudioPrePro " + this.gFf);
        x.d("MicroMsg.CommonInfo", "voipAudioPreProNS " + this.gFg);
        x.d("MicroMsg.CommonInfo", "voipAudioPreProAEC " + this.gFh);
        x.d("MicroMsg.CommonInfo", "voipAudioPreProAGC " + this.gFi);
        x.d("MicroMsg.CommonInfo", "sight full screen type " + this.gFv);
        x.d("MicroMsg.CommonInfo", "checkSightDraftMd5 " + this.gFx);
        x.d("MicroMsg.CommonInfo", "swipeBackConfig " + this.gFy);
        x.d("MicroMsg.CommonInfo", "qrCodeZoom " + this.gFd);
    }
}
