package com.tencent.mm.plugin.sns.h;

import android.os.Process;
import com.tencent.mm.modelsns.d;
import com.tencent.mm.plugin.report.service.g;
import com.tencent.mm.plugin.sns.data.i;
import com.tencent.mm.plugin.sns.model.ae;
import com.tencent.mm.plugin.sns.model.ai;
import com.tencent.mm.plugin.sns.storage.m;
import com.tencent.mm.protocal.c.uo;
import com.tencent.mm.sdk.b.a;
import com.tencent.mm.sdk.platformtools.x;
import com.tencent.mm.z.s;

class b$2 implements Runnable {
    final /* synthetic */ b rdq;
    final /* synthetic */ int rdr;

    public b$2(b bVar, int i) {
        this.rdq = bVar;
        this.rdr = i;
    }

    public final void run() {
        int myTid = Process.myTid();
        x.i("MicroMsg.SnsBrowseInfoHelper", "summersns report tid[%d] osTid[%d], prior[%d][%d]", Long.valueOf(Thread.currentThread().getId()), Integer.valueOf(myTid), Integer.valueOf(Thread.currentThread().getPriority()), Integer.valueOf(Process.getThreadPriority(myTid)));
        long currentTimeMillis = System.currentTimeMillis();
        b bVar = this.rdq;
        int i = this.rdr;
        if (i != -1) {
            m wI = ai.wI(i);
            if (wI != null) {
                String g = i.g(wI);
                bVar.rbJ = g;
                uo byh = ae.bvz().Lq("@__weixintimtline").byh();
                if (byh.wcx == 0 || i.er(byh.wcx).compareTo(g) <= 0) {
                    bVar.iA(false);
                } else {
                    bVar.iA(true);
                }
            }
        }
        i = s.GJ();
        d dVar = new d();
        dVar.q("20BrowseTime", bVar.rbu + ",");
        dVar.q("21BrowseFeedCount", bVar.rbv + ",");
        dVar.q("22CommentOrLikeFeedCount", bVar.rbw + ",");
        dVar.q("23ClickFeedCount", bVar.rbx + ",");
        dVar.q("24ClickAlbumCount", bVar.rby + ",");
        dVar.q("25PostFeedCount", bVar.rbz + ",");
        dVar.q("26ExposeFeedCount", bVar.rcP.size() + ",");
        dVar.q("27FavFeedCount", bVar.rcQ.size() + ",");
        dVar.q("28BlackListFriendCount", bVar.rbC + ",");
        dVar.q("29OutsiderFriendCount", bVar.rbD + ",");
        dVar.q("30BrowseNewFeedCount", bVar.rbE + ",");
        dVar.q("31HasNewSnsMsgWhenEntrance", bVar.rbF + ",");
        dVar.q("32HasNewChatMsgWhenExit", bVar.rbG + ",");
        dVar.q("33StartBrowseSnsObjectId", bVar.rbH + ",");
        dVar.q("34EndBrowseSnsObjectId", bVar.rbI + ",");
        dVar.q("35NextBrowseSnsObjectId", bVar.rbJ + ",");
        dVar.q("36HasNewFeedInServer", bVar.rbK + ",");
        dVar.q("37BrowseBrandUrlFeedCount", bVar.rbL + ",");
        dVar.q("38BrowseNotBrandUrlFeedCount", bVar.rbM + ",");
        dVar.q("39BrowseTextFeedCount", bVar.rbN + ",");
        dVar.q("40BrowseImageFeedCount", bVar.rbO + ",");
        dVar.q("41BrowseSightFeedCount", bVar.rbP + ",");
        dVar.q("42BrowseAdFeedCount", bVar.rbQ + ",");
        dVar.q("43BrowseMusicFeedCount", bVar.rbR + ",");
        dVar.q("44contactCount", i + ",");
        dVar.q("BrowseVideoFeedCount45", bVar.rbS + ",");
        dVar.q("ClickBrandUrlFeedCount46", bVar.rbT + ",");
        dVar.q("ClickNotBrandUrlFeedCount47", bVar.rbU + ",");
        dVar.q("ClickImageFeedCount48", bVar.rbV + ",");
        dVar.q("ClickSightFeedCount49", bVar.rbW + ",");
        dVar.q("ClickMusicFeedCount50", bVar.rbX + ",");
        dVar.q("ClickVideoFeedCount51", bVar.rbY + ",");
        dVar.q("BrowseOtherFeedCount52", bVar.rbZ + ",");
        dVar.q("BrowserStreamVideoFeedCount53", bVar.rca + ",");
        dVar.q("ClickStreamVideoCount54", bVar.rcb + ",");
        dVar.q("ClickAdFeed55", bVar.rcc + ",");
        dVar.q("56BackGroundTime", bVar.rcd + ",");
        dVar.q("57BrowseTimeLineTime", bVar.rcf + ",");
        dVar.q("58BrowseMyAlbumTime", bVar.rch + ",");
        dVar.q("59BrowseOtherAlbumTime", bVar.rcj + ",");
        dVar.q("60BrowseMessageListTime", bVar.rcl + ",");
        dVar.q("61ClickNewPostTime", bVar.rcn + ",");
        dVar.q("62BrowseFullScreenImageTime", bVar.rcp + ",");
        dVar.q("63BrowseFullScreenSightTime", bVar.rcr + ",");
        dVar.q("64BrowseMPArticleTime", bVar.rct + ",");
        dVar.q("65BrowseExternalArticleTime", bVar.rcv + ",");
        dVar.q("66BrowseFullScreenAdImageTime", bVar.rcx + ",");
        dVar.q("67BrowseAdSightTime", "0,");
        dVar.q("68BrowseAdDetailTime", bVar.rcz + ",");
        dVar.q("69BrowseFullScreenAdSightTime", bVar.rcB + ",");
        dVar.q("70BrowseFullScreenAdLongVideoTime", bVar.rcD + ",");
        dVar.q("71BrowseForwardAdLongVideoTime", bVar.rcF + ",");
        dVar.q("72StartBrowseTime", bVar.rdp + ",");
        dVar.q("73ClickFeedIdList", b.f(bVar.rcO) + ",");
        dVar.q("74ExposeFeedIdList", b.f(bVar.rcP) + ",");
        dVar.q("75FavFeedIdList", b.f(bVar.rcQ) + ",");
        dVar.q("76ClickAlbumUserList", b.f(bVar.rcW) + ",");
        dVar.q("77ForwardFeedIdList", b.f(bVar.rcR) + ",");
        dVar.q("78ClickAvatarFeedIdList", b.f(bVar.rcS) + ",");
        dVar.q("79ClickNickNameFeedIdList", b.f(bVar.rcT) + ",");
        dVar.q("80ForwardToSingleChatFeedIdList", b.f(bVar.rcU) + ",");
        dVar.q("81ForwardToChatRoomFeedIdList", b.f(bVar.rcV) + ",");
        dVar.q("82FeedUpdateNotification", bVar.gzm + ",");
        dVar.q("83abandon", ",");
        dVar.q("84abandon", ",");
        dVar.q("85LastestUnReadFeedId", bVar.rcH + ",");
        dVar.q("86UnReadMsgCount", bVar.rcI + ",");
        dVar.q("87BrowseAdCanvasPageTime", bVar.rcJ + ",");
        dVar.q("88BrowseForwardAdCanvasTime", bVar.rcL + ",");
        x.v("MicroMsg.SnsBrowseInfoHelper", "report logbuffer(12076): " + dVar.Sz());
        g.pQN.h(12076, dVar);
        a.xef.c(bVar.gyH);
        bVar.rbu = 0;
        bVar.rbv = 0;
        bVar.rbw = 0;
        bVar.rbx = 0;
        bVar.rby = 0;
        bVar.rbz = 0;
        bVar.rbA = 0;
        bVar.rbB = 0;
        bVar.rbC = 0;
        bVar.rbD = 0;
        bVar.rbE = 0;
        bVar.rbF = 0;
        bVar.rbG = 0;
        bVar.rbH = "";
        bVar.rbI = "";
        bVar.rbJ = "";
        bVar.rbK = 0;
        bVar.rbL = 0;
        bVar.rbM = 0;
        bVar.rbN = 0;
        bVar.rbO = 0;
        bVar.rbP = 0;
        bVar.rbQ = 0;
        bVar.rbR = 0;
        bVar.kGm = 0;
        bVar.rbS = 0;
        bVar.rbT = 0;
        bVar.rbU = 0;
        bVar.rbV = 0;
        bVar.rbW = 0;
        bVar.rbX = 0;
        bVar.rbY = 0;
        bVar.rbZ = 0;
        bVar.rca = 0;
        bVar.rcb = 0;
        bVar.rcc = 0;
        bVar.rcd = 0;
        bVar.rce = 0;
        bVar.rcf = 0;
        bVar.rcg = 0;
        bVar.rch = 0;
        bVar.rci = 0;
        bVar.rcj = 0;
        bVar.rck = 0;
        bVar.rcl = 0;
        bVar.rcm = 0;
        bVar.rcn = 0;
        bVar.rco = 0;
        bVar.rcp = 0;
        bVar.rcq = 0;
        bVar.rcr = 0;
        bVar.rcs = 0;
        bVar.rct = 0;
        bVar.rcu = 0;
        bVar.rcv = 0;
        bVar.rcw = 0;
        bVar.rcx = 0;
        bVar.rcy = 0;
        bVar.rcz = 0;
        bVar.rcA = 0;
        bVar.rcB = 0;
        bVar.rcC = 0;
        bVar.rcD = 0;
        bVar.rcE = 0;
        bVar.rcF = 0;
        bVar.rcG = 0;
        bVar.rcO.clear();
        bVar.rcP.clear();
        bVar.rcQ.clear();
        bVar.rcR.clear();
        bVar.rcS.clear();
        bVar.rcT.clear();
        bVar.rcU.clear();
        bVar.rcV.clear();
        bVar.gzm = 0;
        bVar.rcH = "";
        bVar.rcI = 0;
        x.i("MicroMsg.SnsBrowseInfoHelper", "summersns report take[%d]ms", Long.valueOf(System.currentTimeMillis() - currentTimeMillis));
    }
}
