package com.tencent.mm.plugin.downloader.e;

import com.tencent.mm.g.b.be;
import com.tencent.tmassistantsdk.downloadservice.DownloadInfo;
import com.tencent.tmassistantsdk.openSDK.QQDownloader.AssistantStore.DownloadInfos.DownloadInfoColumns;
import java.lang.reflect.Field;

public final class a extends be {
    protected static com.tencent.mm.sdk.e.c.a gJc;

    static {
        com.tencent.mm.sdk.e.c.a aVar = new com.tencent.mm.sdk.e.c.a();
        aVar.hSY = new Field[25];
        aVar.columns = new String[26];
        StringBuilder stringBuilder = new StringBuilder();
        aVar.columns[0] = "downloadId";
        aVar.xjA.put("downloadId", "LONG default '-1'  PRIMARY KEY ");
        stringBuilder.append(" downloadId LONG default '-1'  PRIMARY KEY ");
        stringBuilder.append(", ");
        aVar.xjz = "downloadId";
        aVar.columns[1] = "downloadUrl";
        aVar.xjA.put("downloadUrl", "TEXT default '' ");
        stringBuilder.append(" downloadUrl TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[2] = DownloadInfo.SECONDARYURL;
        aVar.xjA.put(DownloadInfo.SECONDARYURL, "TEXT default '' ");
        stringBuilder.append(" secondaryUrl TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[3] = "fileSize";
        aVar.xjA.put("fileSize", "LONG default '0' ");
        stringBuilder.append(" fileSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[4] = DownloadInfo.FILENAME;
        aVar.xjA.put(DownloadInfo.FILENAME, "TEXT default '' ");
        stringBuilder.append(" fileName TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[5] = DownloadInfoColumns.FILEPATH;
        aVar.xjA.put(DownloadInfoColumns.FILEPATH, "TEXT default '' ");
        stringBuilder.append(" filePath TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[6] = "fileType";
        aVar.xjA.put("fileType", "INTEGER default '0' ");
        stringBuilder.append(" fileType INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[7] = DownloadInfo.STATUS;
        aVar.xjA.put(DownloadInfo.STATUS, "INTEGER default '0' ");
        stringBuilder.append(" status INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[8] = "md5";
        aVar.xjA.put("md5", "TEXT default '' ");
        stringBuilder.append(" md5 TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[9] = "autoInstall";
        aVar.xjA.put("autoInstall", "INTEGER default 'false' ");
        stringBuilder.append(" autoInstall INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[10] = "showNotification";
        aVar.xjA.put("showNotification", "INTEGER default 'false' ");
        stringBuilder.append(" showNotification INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[11] = "sysDownloadId";
        aVar.xjA.put("sysDownloadId", "LONG default '-1' ");
        stringBuilder.append(" sysDownloadId LONG default '-1' ");
        stringBuilder.append(", ");
        aVar.columns[12] = "downloaderType";
        aVar.xjA.put("downloaderType", "INTEGER default '0' ");
        stringBuilder.append(" downloaderType INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[13] = "appId";
        aVar.xjA.put("appId", "TEXT default '' ");
        stringBuilder.append(" appId TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[14] = "downloadUrlHashCode";
        aVar.xjA.put("downloadUrlHashCode", "INTEGER default '0' ");
        stringBuilder.append(" downloadUrlHashCode INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[15] = DownloadInfoColumns.PACKAGENAME;
        aVar.xjA.put(DownloadInfoColumns.PACKAGENAME, "TEXT default '' ");
        stringBuilder.append(" packageName TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[16] = "downloadedSize";
        aVar.xjA.put("downloadedSize", "LONG default '0' ");
        stringBuilder.append(" downloadedSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[17] = "totalSize";
        aVar.xjA.put("totalSize", "LONG default '0' ");
        stringBuilder.append(" totalSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[18] = "autoDownload";
        aVar.xjA.put("autoDownload", "INTEGER default 'false' ");
        stringBuilder.append(" autoDownload INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[19] = DownloadInfoColumns.CHANNELID;
        aVar.xjA.put(DownloadInfoColumns.CHANNELID, "TEXT default '' ");
        stringBuilder.append(" channelId TEXT default '' ");
        stringBuilder.append(", ");
        aVar.columns[20] = "scene";
        aVar.xjA.put("scene", "INTEGER default '0' ");
        stringBuilder.append(" scene INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[21] = "errCode";
        aVar.xjA.put("errCode", "INTEGER default '0' ");
        stringBuilder.append(" errCode INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[22] = "startTime";
        aVar.xjA.put("startTime", "LONG default '0' ");
        stringBuilder.append(" startTime LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[23] = "startSize";
        aVar.xjA.put("startSize", "LONG default '0' ");
        stringBuilder.append(" startSize LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[24] = "startState";
        aVar.xjA.put("startState", "INTEGER default '0' ");
        stringBuilder.append(" startState INTEGER default '0' ");
        aVar.columns[25] = "rowid";
        aVar.xjB = stringBuilder.toString();
        gJc = aVar;
    }

    protected final com.tencent.mm.sdk.e.c.a Ac() {
        return gJc;
    }
}
