package com.tencent.mm.plugin.sns.ui.a;

import android.view.View;
import android.view.ViewGroup;
import android.view.ViewStub;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.tencent.mm.plugin.appbrand.jsapi.share.i;
import com.tencent.mm.plugin.sns.ui.AsyncNormalTextView;
import com.tencent.mm.plugin.sns.ui.AsyncTextView;
import com.tencent.mm.plugin.sns.ui.MaskTextView;
import com.tencent.mm.plugin.sns.ui.PhotosContent;
import com.tencent.mm.plugin.sns.ui.SnsTranslateResultView;
import com.tencent.mm.plugin.sns.ui.TagImageView;
import com.tencent.mm.plugin.sns.ui.a.g.a;
import com.tencent.mm.plugin.sns.ui.ak;
import com.tencent.mm.plugin.sns.ui.bf;
import com.tencent.mm.protocal.c.aqs;
import com.tencent.mm.protocal.c.bjv;
import com.tencent.mm.protocal.c.bnp;

public class a$c {
    public String frH;
    public String fzW;
    public String iTh;
    public TextView ihS;
    public ImageView iip;
    public int kTK;
    public TextView lUD;
    public View mUL;
    public boolean nbi;
    public int position;
    public bjv qOc;
    public boolean qQH;
    public bf qQI;
    public TextView qSh;
    public TextView rFp;
    public View rFu;
    public long rND;
    public int rNE;
    public AsyncTextView rNF;
    public ImageView rNG;
    public ViewGroup rNH;
    public AsyncNormalTextView rNI;
    public TextView rNJ;
    public TextView rNK;
    public SnsTranslateResultView rNL;
    public View rNM;
    public LinearLayout rNN;
    public ViewStub rNO;
    public boolean rNP = false;
    public TextView rNQ;
    public TagImageView rNR;
    public TextView rNS;
    public int rNT = 0;
    public TextView rNU;
    public AsyncTextView rNV;
    public AsyncTextView rNW;
    public TextView rNX;
    public View rNY;
    public ImageView rNZ;
    public View rOA;
    public ImageView rOB;
    public boolean rOC = false;
    ViewStub rOD;
    boolean rOE = false;
    public ak rOF = new ak();
    public View rOG;
    public boolean rOH = false;
    public a rOI;
    public ak rOJ = new ak();
    public bnp rOK;
    public com.tencent.mm.l.a rOL;
    public View rOM;
    public a rON;
    public ViewStub rOO;
    public View rOP;
    public MaskTextView rOQ;
    public View rOR;
    TextView rOS;
    public String rOT;
    public View rOU;
    public Button rOV;
    public Button rOW;
    public View rOa;
    public MaskTextView rOb;
    public LinearLayout rOc;
    public LinearLayout rOd;
    public View rOe;
    public LinearLayout rOf;
    public PhotosContent rOg;
    public View rOh;
    public ViewStub rOi;
    public boolean rOj = false;
    public ViewStub rOk;
    public ViewStub rOl;
    public View rOm = null;
    public boolean rOn = false;
    public boolean rOo = false;
    public ViewStub rOp;
    public boolean rOq = false;
    public View rOr;
    public LinearLayout rOs;
    public TextView rOt;
    public ViewStub rOu;
    public boolean rOv = false;
    public View rOw;
    public LinearLayout rOx;
    public ViewStub rOy;
    public boolean rOz = false;
    public TextView rkU;
    public aqs roU;
    public LinearLayout rqG;
    public ImageView rrj;
    public TextView rth;
    public int rzT = i.CTRL_INDEX;
}
