package com.tencent.mm.boot.svg.a.a;

import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Paint.Cap;
import android.graphics.Paint.Join;
import android.graphics.Paint.Style;
import android.graphics.Path;
import android.os.Looper;
import com.tencent.mm.svg.WeChatSVGRenderC2Java;
import com.tencent.mm.svg.c;
import com.tencent.smtt.sdk.WebView;

public final class aj extends c {
    private final int height = 54;
    private final int width = 54;

    protected final int b(int i, Object... objArr) {
        switch (i) {
            case 0:
                return 54;
            case 1:
                return 54;
            case 2:
                Canvas canvas = (Canvas) objArr[0];
                Looper looper = (Looper) objArr[1];
                c.f(looper);
                c.e(looper);
                Paint i2 = c.i(looper);
                i2.setFlags(385);
                i2.setStyle(Style.FILL);
                Paint i3 = c.i(looper);
                i3.setFlags(385);
                i3.setStyle(Style.STROKE);
                i2.setColor(WebView.NIGHT_MODE_COLOR);
                i3.setStrokeWidth(1.0f);
                i3.setStrokeCap(Cap.BUTT);
                i3.setStrokeJoin(Join.MITER);
                i3.setStrokeMiter(4.0f);
                i3.setPathEffect(null);
                c.a(i3, looper).setStrokeWidth(1.0f);
                Paint a = c.a(i2, looper);
                a.setColor(-9145228);
                canvas.save();
                Paint a2 = c.a(a, looper);
                Path j = c.j(looper);
                j.moveTo(0.0f, 0.0f);
                j.lineTo(17.995556f, 0.0f);
                j.cubicTo(17.995556f, 5.998519f, 18.005554f, 11.997038f, 17.995556f, 17.995556f);
                j.cubicTo(11.997038f, 18.005554f, 5.998519f, 17.995556f, 0.0f, 17.995556f);
                j.lineTo(0.0f, 0.0f);
                j.lineTo(0.0f, 0.0f);
                j.close();
                j.moveTo(6.0f, 6.0f);
                j.lineTo(6.0f, 12.0f);
                j.lineTo(12.0f, 12.0f);
                j.lineTo(12.0f, 6.0f);
                j.lineTo(6.0f, 6.0f);
                j.lineTo(6.0f, 6.0f);
                j.close();
                WeChatSVGRenderC2Java.setFillType(j, 2);
                canvas.drawPath(j, a2);
                canvas.restore();
                canvas.save();
                a2 = c.a(a, looper);
                j = c.j(looper);
                j.moveTo(24.0f, 0.0f);
                j.lineTo(36.0f, 0.0f);
                j.lineTo(36.0f, 6.0f);
                j.lineTo(42.0f, 6.0f);
                j.lineTo(42.0f, 12.0f);
                j.lineTo(30.0f, 12.0f);
                j.lineTo(30.0f, 6.01f);
                j.cubicTo(28.0f, 6.0f, 26.0f, 6.0f, 24.0f, 5.99f);
                j.lineTo(24.0f, 0.0f);
                j.lineTo(24.0f, 0.0f);
                j.close();
                WeChatSVGRenderC2Java.setFillType(j, 2);
                canvas.drawPath(j, a2);
                canvas.restore();
                canvas.save();
                a2 = c.a(a, looper);
                j = c.j(looper);
                j.moveTo(42.0f, 0.0f);
                j.lineTo(54.0f, 0.0f);
                j.lineTo(54.0f, 24.0f);
                j.lineTo(48.01f, 24.0f);
                j.cubicTo(48.0f, 22.0f, 48.0f, 20.0f, 47.99f, 18.0f);
                j.lineTo(42.0f, 18.0f);
                j.lineTo(42.0f, 12.0f);
                j.lineTo(48.0f, 12.0f);
                j.lineTo(48.0f, 6.0f);
                j.lineTo(42.0f, 6.0f);
                j.lineTo(42.0f, 0.0f);
                j.lineTo(42.0f, 0.0f);
                j.close();
                WeChatSVGRenderC2Java.setFillType(j, 2);
                canvas.drawPath(j, a2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                Path j2 = c.j(looper);
                j2.moveTo(24.0f, 12.0f);
                j2.lineTo(30.0f, 12.0f);
                j2.lineTo(30.0f, 18.0f);
                j2.lineTo(24.0f, 18.0f);
                j2.lineTo(24.0f, 12.0f);
                j2.lineTo(24.0f, 12.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(30.0f, 18.0f);
                j2.lineTo(42.0f, 18.0f);
                j2.lineTo(42.0f, 24.0f);
                j2.lineTo(36.0f, 24.0f);
                j2.lineTo(36.0f, 30.0f);
                j2.lineTo(24.0f, 30.0f);
                j2.lineTo(24.0f, 36.0f);
                j2.lineTo(12.0f, 36.0f);
                j2.lineTo(12.0f, 30.0f);
                j2.lineTo(18.0f, 30.0f);
                j2.lineTo(18.0f, 24.0f);
                j2.lineTo(30.0f, 24.0f);
                j2.lineTo(30.0f, 18.0f);
                j2.lineTo(30.0f, 18.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(0.0f, 24.0f);
                j2.lineTo(12.0f, 24.0f);
                j2.lineTo(12.0f, 30.0f);
                j2.lineTo(6.0f, 30.0f);
                j2.lineTo(6.0f, 36.0f);
                j2.lineTo(0.0f, 36.0f);
                j2.lineTo(0.0f, 24.0f);
                j2.lineTo(0.0f, 24.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(36.0f, 30.0f);
                j2.lineTo(42.0f, 30.0f);
                j2.lineTo(42.0f, 36.0f);
                j2.lineTo(36.0f, 36.0f);
                j2.lineTo(36.0f, 30.0f);
                j2.lineTo(36.0f, 30.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                a2 = c.a(a, looper);
                j = c.j(looper);
                j.moveTo(48.0f, 30.0f);
                j.lineTo(54.0f, 30.0f);
                j.lineTo(54.0f, 42.0f);
                j.lineTo(48.0f, 42.0f);
                j.lineTo(48.0f, 48.0f);
                j.lineTo(54.0f, 48.0f);
                j.lineTo(54.0f, 54.0f);
                j.lineTo(42.0f, 54.0f);
                j.lineTo(42.0f, 48.0f);
                j.lineTo(36.0f, 48.0f);
                j.lineTo(36.0f, 42.0f);
                j.lineTo(42.0f, 42.0f);
                j.lineTo(42.0f, 36.0f);
                j.lineTo(47.99f, 36.0f);
                j.cubicTo(48.0f, 34.0f, 48.0f, 32.0f, 48.0f, 30.0f);
                j.lineTo(48.0f, 30.0f);
                j.close();
                WeChatSVGRenderC2Java.setFillType(j, 2);
                canvas.drawPath(j, a2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(6.0f, 36.0f);
                j2.lineTo(12.0f, 36.0f);
                j2.lineTo(12.0f, 42.0f);
                j2.lineTo(6.0f, 42.0f);
                j2.lineTo(6.0f, 36.0f);
                j2.lineTo(6.0f, 36.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(24.0f, 36.0f);
                j2.lineTo(36.0f, 36.0f);
                j2.lineTo(36.0f, 42.0f);
                j2.lineTo(24.0f, 42.0f);
                j2.lineTo(24.0f, 36.0f);
                j2.lineTo(24.0f, 36.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(0.0f, 42.0f);
                j2.lineTo(6.0f, 42.0f);
                j2.lineTo(6.0f, 48.0f);
                j2.lineTo(18.0f, 48.0f);
                j2.lineTo(18.0f, 54.0f);
                j2.lineTo(0.0f, 54.0f);
                j2.lineTo(0.0f, 42.0f);
                j2.lineTo(0.0f, 42.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(18.0f, 42.0f);
                j2.lineTo(24.0f, 42.0f);
                j2.lineTo(24.0f, 48.0f);
                j2.lineTo(18.0f, 48.0f);
                j2.lineTo(18.0f, 42.0f);
                j2.lineTo(18.0f, 42.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                j2 = c.j(looper);
                j2.moveTo(24.0f, 48.0f);
                j2.lineTo(36.0f, 48.0f);
                j2.lineTo(36.0f, 54.0f);
                j2.lineTo(24.0f, 54.0f);
                j2.lineTo(24.0f, 48.0f);
                j2.lineTo(24.0f, 48.0f);
                j2.close();
                WeChatSVGRenderC2Java.setFillType(j2, 2);
                canvas.drawPath(j2, i2);
                canvas.restore();
                c.h(looper);
                break;
        }
        return 0;
    }
}
