package com.tencent.mm.boot.svg.a.a;

import android.graphics.Canvas;
import android.graphics.Matrix;
import android.graphics.Paint;
import android.graphics.Paint.Cap;
import android.graphics.Paint.Join;
import android.graphics.Paint.Style;
import android.graphics.Path;
import android.os.Looper;
import com.tencent.mm.svg.c;
import com.tencent.smtt.sdk.WebView;
import com.tencent.tmassistantsdk.downloadservice.DownloadHelper;

public final class mu extends c {
    private final int height = 245;
    private final int width = 357;

    protected final int b(int i, Object... objArr) {
        switch (i) {
            case 0:
                return 357;
            case 1:
                return 245;
            case 2:
                Canvas canvas = (Canvas) objArr[0];
                Looper looper = (Looper) objArr[1];
                Matrix f = c.f(looper);
                float[] e = c.e(looper);
                Paint i2 = c.i(looper);
                i2.setFlags(385);
                i2.setStyle(Style.FILL);
                Paint i3 = c.i(looper);
                i3.setFlags(385);
                i3.setStyle(Style.STROKE);
                i2.setColor(WebView.NIGHT_MODE_COLOR);
                i3.setStrokeWidth(1.0f);
                i3.setStrokeCap(Cap.BUTT);
                i3.setStrokeJoin(Join.MITER);
                i3.setStrokeMiter(4.0f);
                i3.setPathEffect(null);
                Paint a = c.a(i3, looper);
                a.setStrokeWidth(1.0f);
                canvas.save();
                i3 = c.a(i2, looper);
                i3.setColor(WebView.NIGHT_MODE_COLOR);
                Path j = c.j(looper);
                j.moveTo(20.0f, 0.0f);
                j.lineTo(21.0f, 0.0f);
                j.lineTo(21.0f, 245.0f);
                j.lineTo(20.0f, 245.0f);
                j.lineTo(20.0f, 0.0f);
                j.close();
                canvas.drawPath(j, i3);
                canvas.restore();
                canvas.save();
                i2 = c.a(i2, looper);
                i2.setColor(WebView.NIGHT_MODE_COLOR);
                Path j2 = c.j(looper);
                j2.moveTo(335.0f, 0.0f);
                j2.lineTo(336.0f, 0.0f);
                j2.lineTo(336.0f, 245.0f);
                j2.lineTo(335.0f, 245.0f);
                j2.lineTo(335.0f, 0.0f);
                j2.close();
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                i2 = c.a(a, looper);
                i2.setColor(WebView.NIGHT_MODE_COLOR);
                i2.setStrokeWidth(3.0f);
                j2 = c.j(looper);
                j2.moveTo(8.790844f, DownloadHelper.SAVE_FATOR);
                j2.lineTo(1.506977f, 243.5f);
                j2.lineTo(355.493f, 243.5f);
                j2.lineTo(348.20917f, DownloadHelper.SAVE_FATOR);
                j2.lineTo(8.790844f, DownloadHelper.SAVE_FATOR);
                j2.close();
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.save();
                Paint a2 = c.a(a, looper);
                a2.setColor(WebView.NIGHT_MODE_COLOR);
                e = c.a(e, 1.0f, 0.0f, 37.0f, 0.0f, 1.0f, 25.0f);
                f.reset();
                f.setValues(e);
                canvas.concat(f);
                canvas.save();
                i2 = c.a(a2, looper);
                j2 = c.j(looper);
                j2.moveTo(-0.5f, -0.5f);
                j2.lineTo(285.5f, -0.5f);
                j2.lineTo(285.5f, 192.5f);
                j2.lineTo(-0.5f, 192.5f);
                j2.lineTo(-0.5f, -0.5f);
                j2.close();
                canvas.drawPath(j2, i2);
                canvas.restore();
                canvas.restore();
                canvas.save();
                a = c.a(a, looper);
                a.setColor(WebView.NIGHT_MODE_COLOR);
                a.setStrokeWidth(2.0f);
                e = c.a(e, 1.0f, 0.0f, 134.0f, 0.0f, 1.0f, 97.0f);
                f.reset();
                f.setValues(e);
                canvas.concat(f);
                canvas.save();
                Paint a3 = c.a(a, looper);
                Path j3 = c.j(looper);
                j3.moveTo(1.0f, 3.0f);
                j3.cubicTo(1.0f, 1.8954304f, 1.8954304f, 1.0f, 3.0f, 1.0f);
                j3.lineTo(66.0f, 1.0f);
                j3.cubicTo(67.10457f, 1.0f, 68.0f, 1.8954304f, 68.0f, 3.0f);
                j3.lineTo(68.0f, 49.0f);
                j3.cubicTo(68.0f, 50.10457f, 67.10457f, 51.0f, 66.0f, 51.0f);
                j3.lineTo(3.0f, 51.0f);
                j3.cubicTo(1.8954304f, 51.0f, 1.0f, 50.10457f, 1.0f, 49.0f);
                j3.lineTo(1.0f, 3.0f);
                j3.close();
                canvas.drawPath(j3, a3);
                canvas.restore();
                canvas.save();
                a3 = c.a(a, looper);
                j3 = c.j(looper);
                j3.moveTo(99.0f, 50.07509f);
                j3.lineTo(99.0f, 2.0108225f);
                j3.lineTo(75.39577f, 19.873486f);
                j3.cubicTo(75.21011f, 20.013983f, 75.0f, 20.437353f, 75.0f, 20.675142f);
                j3.lineTo(75.0f, 32.730263f);
                j3.cubicTo(75.0f, 32.953712f, 75.21011f, 33.357872f, 75.39602f, 33.488506f);
                j3.lineTo(99.0f, 50.07509f);
                j3.close();
                canvas.drawPath(j3, a3);
                canvas.restore();
                canvas.restore();
                c.h(looper);
                break;
        }
        return 0;
    }
}
